baseurl = "http://Hotpotato00.github.io/"
title = "Dony's Blog"
theme = "cleanwhite"
languageCode = "kr-ko"
# Enable comments by entering your Disqus shortname
#disqusShortname = ""
googleAnalytics = "UA-109223766-1"
#preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/gala.jpg"
  SEOTitle = "갈라파고스를 꿈꾸는 개발자"
  #description = "갈라파고스를 꿈꾸는 개발자"
  keyword = "프로그래머, Dony, ICBMA, Dony's Blog"
  slogan = "여유를 가질 때，행복해진다."

  image_404 = "img/404-bg.jpg"
  title_404 = "404에러 입니다. :("

  # leancloud storage for page view counter
  # page_view_conter = true
  # leancloud_app_id = "Xu5MAnXL360Ms89vMVnWBjuq-gzGzoHsz"
  # leancloud_app_key = "efUYEefAc2eIPBRO59PRERQC"

  # algolia site search
  #algolia_search = true
  #algolia_appId = "WM4BEY1UDN"
  #algolia_indexName = "blog"
  #algolia_apiKey = "090c4a77b8bd4b8d2f2c1262afbc4be2"

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/sd.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  # Baidu Analytics
  # ba_track_id = "a1d96090e4189c0376251fb043da7be5"

  # We need a proxy to access Disqus api in China
  # disqus_proxy = "https://disqusapi.zhaohuabing.com"
  # disqus_site = "http://Hotpotato00.github.io/"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  # reward = true
  # reward_guide = "如果这篇文章对你有用,请随意打赏"

  # friends = true
  # bookmarks = true
  about_me = true

  [params.social]
  rss            = true
  email          = "hotpotatto@naver.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/zhaohuabing"
  #stackoverflow  = "https://stackoverflow.com/users/2306565/huabing-zhao"
  instagram     = "http://www.instagram.com/hotpotato00"
  github         = "https://github.com/hotpotato00"
  #wechat         = "http://Hotpotato00.github.io//img/wechat_qrcode.jpg"
  #medium         = "https://medium.com/@zhaohuabing"
  #pinterest     = "full profile url in pinterest"

  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"
  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title = "Awesome Service Mesh"
  #href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  #[[params.bookmark_link]]
  #title =  "Image Compression"
  #href = "https://tinypng.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"

#[outputFormats.Algolia]
#baseName = "algolia"
#isPlainText = true
#mediaType = "application/json"
#notAlternative = true

#[params.algolia]
#vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
#params = ["categories", "tags"]
